// <auto-generated />
namespace EIndeks.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addStudentToOcena : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addStudentToOcena));
        
        string IMigrationMetadata.Id
        {
            get { return "202001272055219_addStudentToOcena"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
